/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import app.Projeto_GYM;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.channels.FileChannel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Academia;

/**
 *
 * @author Insinuante
 */
public class AcademiaCadastroJFrame extends javax.swing.JFrame {

    private Academia a;

    /**
     * Creates new form AlunosJFrame
     */
    public AcademiaCadastroJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanelBack = new javax.swing.JPanel();
        jPanelBlue = new javax.swing.JPanel();
        jLabeAlunos = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelCpf = new javax.swing.JLabel();
        jFormattedTextFieldCPF1 = new javax.swing.JFormattedTextField();
        jLabelCNPJ = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelEmail1 = new javax.swing.JLabel();
        jComboBoxSexo3 = new javax.swing.JComboBox<>();
        jFormattedTextFieldCEP1 = new javax.swing.JFormattedTextField();
        jLabelCEP1 = new javax.swing.JLabel();
        jLabelUF1 = new javax.swing.JLabel();
        jTextFieldBairro1 = new javax.swing.JTextField();
        jLabelBairro1 = new javax.swing.JLabel();
        jTextFieldLogradouro3 = new javax.swing.JTextField();
        jLabelLogradouro1 = new javax.swing.JLabel();
        jTextFieldNomeF = new javax.swing.JTextField();
        jLabelNomeF = new javax.swing.JLabel();
        jTextFieldNomeP = new javax.swing.JTextField();
        jLabelCNPJ1 = new javax.swing.JLabel();
        jFormattedTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelCidade1 = new javax.swing.JLabel();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        logojPanel = new javax.swing.JPanel();
        logoAcademiajLabel = new javax.swing.JLabel();
        jLabelCpf1 = new javax.swing.JLabel();
        addjButton = new javax.swing.JButton();
        removjButton = new javax.swing.JButton();
        jFormattedTextFieldNum = new javax.swing.JFormattedTextField();
        jLabelUF2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro  de aluno");

        jPanelBack.setBackground(new java.awt.Color(255, 255, 255));

        jPanelBlue.setBackground(new java.awt.Color(45, 118, 232));

        jLabeAlunos.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabeAlunos.setForeground(new java.awt.Color(255, 255, 255));
        jLabeAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Gym_50px.png"))); // NOI18N
        jLabeAlunos.setText(" Academia");

        javax.swing.GroupLayout jPanelBlueLayout = new javax.swing.GroupLayout(jPanelBlue);
        jPanelBlue.setLayout(jPanelBlueLayout);
        jPanelBlueLayout.setHorizontalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBlueLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabeAlunos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBlueLayout.setVerticalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBlueLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabeAlunos)
                .addGap(28, 28, 28))
        );

        jButtonSalvar.setBackground(new java.awt.Color(45, 118, 232));
        jButtonSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(45, 118, 232));
        jButtonCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(45, 118, 232));
        jLabelNome.setText("Nome");

        jTextFieldNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabelCpf.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCpf.setForeground(new java.awt.Color(45, 118, 232));
        jLabelCpf.setText("CPF");

        try {
            jFormattedTextFieldCPF1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jFormattedTextFieldCPF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPF1ActionPerformed(evt);
            }
        });

        jLabelCNPJ.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCNPJ.setForeground(new java.awt.Color(45, 118, 232));
        jLabelCNPJ.setText("CNPJ");

        jLabelCelular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCelular.setForeground(new java.awt.Color(45, 118, 232));
        jLabelCelular.setText("Celular");

        jLabelCidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCidade.setForeground(new java.awt.Color(45, 118, 232));
        jLabelCidade.setText("Cidade");

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jFormattedTextFieldCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCelularActionPerformed(evt);
            }
        });

        jTextFieldEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabelEmail1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelEmail1.setForeground(new java.awt.Color(45, 118, 232));
        jLabelEmail1.setText("E-mail");

        jComboBoxSexo3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBoxSexo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        jComboBoxSexo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexo3ActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCEP1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCEP1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jFormattedTextFieldCEP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCEP1ActionPerformed(evt);
            }
        });

        jLabelCEP1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCEP1.setForeground(new java.awt.Color(45, 118, 232));
        jLabelCEP1.setText("CEP");

        jLabelUF1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelUF1.setForeground(new java.awt.Color(45, 118, 232));
        jLabelUF1.setText("UF");

        jTextFieldBairro1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldBairro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairro1ActionPerformed(evt);
            }
        });

        jLabelBairro1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelBairro1.setForeground(new java.awt.Color(45, 118, 232));
        jLabelBairro1.setText("Bairro");

        jTextFieldLogradouro3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldLogradouro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLogradouro3ActionPerformed(evt);
            }
        });

        jLabelLogradouro1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelLogradouro1.setForeground(new java.awt.Color(45, 118, 232));
        jLabelLogradouro1.setText("Logradouro");

        jTextFieldNomeF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldNomeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeFActionPerformed(evt);
            }
        });

        jLabelNomeF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelNomeF.setForeground(new java.awt.Color(45, 118, 232));
        jLabelNomeF.setText("Nome fantasia");

        jTextFieldNomeP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldNomeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomePActionPerformed(evt);
            }
        });

        jLabelCNPJ1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCNPJ1.setForeground(new java.awt.Color(45, 118, 232));
        jLabelCNPJ1.setText("Nome do proprietário");

        try {
            jFormattedTextFieldCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCNPJ.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jFormattedTextFieldCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCNPJActionPerformed(evt);
            }
        });

        jTextFieldCidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeActionPerformed(evt);
            }
        });

        jLabelCidade1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCidade1.setForeground(new java.awt.Color(45, 118, 232));
        jLabelCidade1.setText("Telefone");

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jFormattedTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefoneActionPerformed(evt);
            }
        });

        logojPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logoAcademiajLabel.setText("                             Inserir logo");

        javax.swing.GroupLayout logojPanelLayout = new javax.swing.GroupLayout(logojPanel);
        logojPanel.setLayout(logojPanelLayout);
        logojPanelLayout.setHorizontalGroup(
            logojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoAcademiajLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logojPanelLayout.setVerticalGroup(
            logojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoAcademiajLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );

        jLabelCpf1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCpf1.setForeground(new java.awt.Color(45, 118, 232));
        jLabelCpf1.setText("Logo da academia:");

        addjButton.setBackground(new java.awt.Color(45, 118, 232));
        addjButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addjButton.setForeground(new java.awt.Color(255, 255, 255));
        addjButton.setText("Adicionar logo");
        addjButton.setToolTipText("Salvar");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });

        removjButton.setBackground(new java.awt.Color(45, 118, 232));
        removjButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        removjButton.setForeground(new java.awt.Color(255, 255, 255));
        removjButton.setText("Remover logo");
        removjButton.setToolTipText("Salvar");
        removjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removjButtonActionPerformed(evt);
            }
        });

        jFormattedTextFieldNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabelUF2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelUF2.setForeground(new java.awt.Color(45, 118, 232));
        jLabelUF2.setText("N°");

        javax.swing.GroupLayout jPanelBackLayout = new javax.swing.GroupLayout(jPanelBack);
        jPanelBack.setLayout(jPanelBackLayout);
        jPanelBackLayout.setHorizontalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBackLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackLayout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackLayout.createSequentialGroup()
                        .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBackLayout.createSequentialGroup()
                                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBackLayout.createSequentialGroup()
                                        .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNomeF)
                                            .addGroup(jPanelBackLayout.createSequentialGroup()
                                                .addComponent(jLabelNomeF)
                                                .addGap(0, 133, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelCNPJ)))
                                    .addComponent(jTextFieldNomeP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLogradouro3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBackLayout.createSequentialGroup()
                                        .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCNPJ1)
                                            .addComponent(jLabelLogradouro1)
                                            .addComponent(jLabelEmail1))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelCpf)
                                    .addComponent(jLabelBairro1)
                                    .addComponent(jTextFieldBairro1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jFormattedTextFieldCEP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextFieldCPF1)
                                    .addComponent(jLabelCidade1)
                                    .addComponent(jFormattedTextFieldTelefone)
                                    .addComponent(jLabelCEP1))))
                        .addGap(11, 11, 11)))
                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelCpf1)
                        .addComponent(logojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelBackLayout.createSequentialGroup()
                            .addComponent(addjButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(removjButton)))
                    .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelBackLayout.createSequentialGroup()
                            .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelBackLayout.createSequentialGroup()
                            .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCidade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                                .addComponent(jLabelCelular))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelUF2)
                                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxSexo3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelUF1)
                                    .addComponent(jFormattedTextFieldNum))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanelBackLayout.setVerticalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackLayout.createSequentialGroup()
                .addComponent(jPanelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelCpf1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackLayout.createSequentialGroup()
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBackLayout.createSequentialGroup()
                                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNomeF)
                                    .addComponent(jLabelCNPJ))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelBackLayout.createSequentialGroup()
                                .addComponent(jLabelCpf)
                                .addGap(11, 11, 11)
                                .addComponent(jFormattedTextFieldCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCNPJ1)
                            .addComponent(jLabelBairro1)))
                    .addComponent(logojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackLayout.createSequentialGroup()
                        .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelBackLayout.createSequentialGroup()
                                .addComponent(jLabelLogradouro1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLogradouro3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBackLayout.createSequentialGroup()
                                .addComponent(jLabelCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackLayout.createSequentialGroup()
                        .addComponent(jLabelCEP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldCEP1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackLayout.createSequentialGroup()
                        .addComponent(jLabelUF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSexo3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBackLayout.createSequentialGroup()
                        .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCidade1)
                            .addComponent(jLabelEmail1)
                            .addComponent(jLabelCelular)
                            .addComponent(jLabelUF2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        addjButton.getAccessibleContext().setAccessibleDescription("Adicionar");
        removjButton.getAccessibleContext().setAccessibleDescription("Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(856, 613));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jFormattedTextFieldCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCelularActionPerformed

    private void jFormattedTextFieldCPF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPF1ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
        new AlunosHomeJFrame().show();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Projeto_GYM.fachada.cadastrarEndereco(a.getEndereco());
        Projeto_GYM.fachada.cadastrarAcademia(a);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jComboBoxSexo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexo3ActionPerformed

    private void jFormattedTextFieldCEP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCEP1ActionPerformed

    private void jTextFieldBairro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairro1ActionPerformed

    private void jTextFieldLogradouro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLogradouro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLogradouro3ActionPerformed

    private void jTextFieldNomeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFActionPerformed

    private void jTextFieldNomePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomePActionPerformed

    private void jFormattedTextFieldCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCNPJActionPerformed

    private void jTextFieldCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeActionPerformed

    private void jFormattedTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelefoneActionPerformed

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        a.setLogo(copy(this));
        logoAcademiajLabel.setIcon(new ImageIcon(a.getLogo()));
    }//GEN-LAST:event_addjButtonActionPerformed

    private void removjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removjButtonActionPerformed
        a.setLogo("");
        logoAcademiajLabel.setText("Inserir logo");
    }//GEN-LAST:event_removjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxSexo3;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldNum;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabeAlunos;
    private javax.swing.JLabel jLabelBairro1;
    private javax.swing.JLabel jLabelCEP1;
    private javax.swing.JLabel jLabelCNPJ;
    private javax.swing.JLabel jLabelCNPJ1;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCidade1;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelCpf1;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelLogradouro1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeF;
    private javax.swing.JLabel jLabelUF1;
    private javax.swing.JLabel jLabelUF2;
    private javax.swing.JPanel jPanelBack;
    private javax.swing.JPanel jPanelBlue;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextFieldBairro1;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldLogradouro3;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeF;
    private javax.swing.JTextField jTextFieldNomeP;
    private javax.swing.JLabel logoAcademiajLabel;
    private javax.swing.JPanel logojPanel;
    private javax.swing.JButton removjButton;
    // End of variables declaration//GEN-END:variables

    private Academia get(){
        a.setCelular(jFormattedTextFieldCelular.getText());
        a.setCnpj(jFormattedTextFieldCNPJ.getText());
        a.setCpf(jFormattedTextFieldCPF1.getText());
        a.setEmail(jTextFieldEmail.getText());
        a.getEndereco().setBairro(jTextFieldBairro1.getText());
        a.getEndereco().setCep(jFormattedTextFieldCEP1.getText());
        a.getEndereco().setCidade(jTextFieldCidade.getText());
        a.getEndereco().setLogradouro(jTextFieldLogradouro3.getText());
        a.getEndereco().setNum(Integer.parseInt(jFormattedTextFieldNum.getText()));
        a.getEndereco().setUf(jComboBoxSexo3.getSelectedItem()+"");
        a.setNome(jTextFieldNome.getText());
        a.setNomeFantasia(jTextFieldNomeF.getText());
        a.setNomeProprietario(jTextFieldNomeP.getText());
        a.setTelefone(jFormattedTextFieldTelefone.getText());
        
        return a;
    }
    
    
    

    private static String copy(JFrame tela) {
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(tela);
            File file = chooser.getSelectedFile();

            String l = file.getAbsolutePath();
            String i = "";

            i = "src/imagens/" + file.getName();            

            FileInputStream fisDe = new FileInputStream(l);
            FileOutputStream fisPara = new FileOutputStream(i);

            FileChannel fcPara = fisDe.getChannel();
            FileChannel fcDe = fisPara.getChannel();

            if (fcPara.transferTo(0, fcPara.size(), fcDe) == 0L) {
                fcPara.close();
                fcDe.close();
            }
            return i;
        } catch (Exception x) {
            JOptionPane.showMessageDialog(null, x);
        }
        return null;
    }
}
