/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import app.Projeto_GYM;
import app.Util;
import java.sql.Date;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Aluno;
import model.Endereco;

/**
 *
 * @author Insinuante
 */
public class AlunosCadastroJFrame extends javax.swing.JFrame {
    Aluno a;
    /**
     * Creates new form AlunosJFrame
     */
    public AlunosCadastroJFrame() {
        initComponents();
        a=new Aluno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanelBack = new javax.swing.JPanel();
        jPanelBlue = new javax.swing.JPanel();
        jLabeAlunos = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCadastro = new javax.swing.JPanel();
        jLabelId = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelRg = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelDN = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldDN = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jTextFieldRG = new javax.swing.JTextField();
        jComboBoxUF = new javax.swing.JComboBox<>();
        jLabelCidade = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jLabelUF = new javax.swing.JLabel();
        jLabelCEP = new javax.swing.JLabel();
        jLabelLogradouro = new javax.swing.JLabel();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jComboBoxSexo1 = new javax.swing.JComboBox<>();
        jFormattedTextFieldCPF1 = new javax.swing.JFormattedTextField();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jTextFieldemail = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jPanelAdicinais = new javax.swing.JPanel();
        jLabelDados = new javax.swing.JLabel();
        jLabeAV = new javax.swing.JLabel();
        jLabelFicha = new javax.swing.JLabel();
        jLabelObjetivo = new javax.swing.JLabel();
        jLabelObs = new javax.swing.JLabel();
        jScrollPaneObs = new javax.swing.JScrollPane();
        jTextAreaObs = new javax.swing.JTextArea();
        jScrollObj = new javax.swing.JScrollPane();
        jTextAreaObj = new javax.swing.JTextArea();
        jPanelAvalicao = new javax.swing.JPanel();
        jLabeOpenAV = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelFicha = new javax.swing.JPanel();
        jLabeOpenFicha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelPagamentos = new javax.swing.JPanel();
        jLabelPagamentos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSalvar1 = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro  de aluno");

        jPanelBack.setBackground(new java.awt.Color(255, 255, 255));

        jPanelBlue.setBackground(new java.awt.Color(45, 118, 232));

        jLabeAlunos.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabeAlunos.setForeground(new java.awt.Color(255, 255, 255));
        jLabeAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_52px_1.png"))); // NOI18N
        jLabeAlunos.setText(" Alunos ");

        javax.swing.GroupLayout jPanelBlueLayout = new javax.swing.GroupLayout(jPanelBlue);
        jPanelBlue.setLayout(jPanelBlueLayout);
        jPanelBlueLayout.setHorizontalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBlueLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabeAlunos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBlueLayout.setVerticalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBlueLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabeAlunos)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.setBackground(new java.awt.Color(45, 118, 232));
        jTabbedPane1.setToolTipText("Dados adicionais");

        jPanelCadastro.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadastro.setToolTipText("Cadastrar Aluno");

        jLabelId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(45, 118, 232));
        jLabelId.setText("Id");

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(45, 118, 232));
        jLabelNome.setText("Nome");

        jLabelCpf.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCpf.setForeground(new java.awt.Color(45, 118, 232));
        jLabelCpf.setText("CPF");

        jLabelRg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelRg.setForeground(new java.awt.Color(45, 118, 232));
        jLabelRg.setText("RG");

        jLabelSexo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(45, 118, 232));
        jLabelSexo.setText("Sexo");

        jLabelDN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelDN.setForeground(new java.awt.Color(45, 118, 232));
        jLabelDN.setText("Data nascimento");

        jLabelEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(45, 118, 232));
        jLabelEmail.setText("E-mail");

        jLabelStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(45, 118, 232));
        jLabelStatus.setText("Status");

        jTextFieldId.setEditable(false);
        jTextFieldId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        jTextFieldNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jFormattedTextFieldDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDNActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCEP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jFormattedTextFieldCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCEPActionPerformed(evt);
            }
        });

        jTextFieldRG.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRGActionPerformed(evt);
            }
        });

        jComboBoxUF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBoxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        jComboBoxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUFActionPerformed(evt);
            }
        });

        jLabelCidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCidade.setForeground(new java.awt.Color(45, 118, 232));
        jLabelCidade.setText("Cidade");

        jLabelBairro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelBairro.setForeground(new java.awt.Color(45, 118, 232));
        jLabelBairro.setText("Bairro");

        jLabelCelular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCelular.setForeground(new java.awt.Color(45, 118, 232));
        jLabelCelular.setText("Celular");

        jLabelUF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelUF.setForeground(new java.awt.Color(45, 118, 232));
        jLabelUF.setText("UF");

        jLabelCEP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCEP.setForeground(new java.awt.Color(45, 118, 232));
        jLabelCEP.setText("CEP");

        jLabelLogradouro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelLogradouro.setForeground(new java.awt.Color(45, 118, 232));
        jLabelLogradouro.setText("Logradouro");

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jFormattedTextFieldCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCelularActionPerformed(evt);
            }
        });

        jTextFieldLogradouro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLogradouroActionPerformed(evt);
            }
        });

        jTextFieldCidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeActionPerformed(evt);
            }
        });

        jTextFieldBairro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });

        jComboBoxSexo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBoxSexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));
        jComboBoxSexo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexo1ActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCPF1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jFormattedTextFieldCPF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPF1ActionPerformed(evt);
            }
        });

        jComboBoxStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        jComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusActionPerformed(evt);
            }
        });

        jTextFieldemail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldemailActionPerformed(evt);
            }
        });

        jTextFieldNumero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });

        jLabelNumero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(45, 118, 232));
        jLabelNumero.setText("Número");

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabelLogradouro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldemail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelBairro))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNumero)
                                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelUF)
                                            .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCEP)
                                            .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                .addComponent(jLabelCpf)
                                                .addGap(125, 125, 125))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                                                .addComponent(jFormattedTextFieldCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                .addComponent(jLabelRg)
                                                .addGap(196, 196, 196))
                                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                .addComponent(jTextFieldRG)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                                .addComponent(jLabelSexo)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jComboBoxSexo1, 0, 82, Short.MAX_VALUE)))
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelId, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelDN)
                                            .addComponent(jFormattedTextFieldDN)
                                            .addComponent(jLabelCelular)
                                            .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCidade)
                                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelStatus)
                                                .addComponent(jTextFieldCidade)
                                                .addComponent(jComboBoxStatus, 0, 106, Short.MAX_VALUE)))))))
                        .addContainerGap(65, Short.MAX_VALUE))))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelDN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf)
                    .addComponent(jLabelRg)
                    .addComponent(jLabelSexo)
                    .addComponent(jLabelCelular))
                .addGap(11, 11, 11)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogradouro)
                    .addComponent(jLabelCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairro)
                    .addComponent(jLabelUF)
                    .addComponent(jLabelCEP)
                    .addComponent(jLabelStatus)
                    .addComponent(jLabelNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar", jPanelCadastro);

        jPanelAdicinais.setBackground(new java.awt.Color(255, 255, 255));

        jLabelDados.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabelDados.setForeground(new java.awt.Color(45, 118, 232));
        jLabelDados.setText("Dados Adicionais");

        jLabeAV.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeAV.setForeground(new java.awt.Color(45, 118, 232));
        jLabeAV.setText("Avaliação Física");

        jLabelFicha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelFicha.setForeground(new java.awt.Color(45, 118, 232));
        jLabelFicha.setText("Ficha Treino");

        jLabelObjetivo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelObjetivo.setForeground(new java.awt.Color(45, 118, 232));
        jLabelObjetivo.setText("Objetivo");

        jLabelObs.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelObs.setForeground(new java.awt.Color(45, 118, 232));
        jLabelObs.setText("Observações");

        jTextAreaObs.setColumns(20);
        jTextAreaObs.setRows(5);
        jScrollPaneObs.setViewportView(jTextAreaObs);

        jTextAreaObj.setColumns(20);
        jTextAreaObj.setRows(5);
        jScrollObj.setViewportView(jTextAreaObj);

        jPanelAvalicao.setToolTipText("Avaliação física");
        jPanelAvalicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAvalicaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAvalicaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelAvalicaoMousePressed(evt);
            }
        });

        jLabeOpenAV.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeOpenAV.setForeground(new java.awt.Color(45, 118, 232));
        jLabeOpenAV.setText("Abrir avaliação física");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AV_Blue.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAvalicaoLayout = new javax.swing.GroupLayout(jPanelAvalicao);
        jPanelAvalicao.setLayout(jPanelAvalicaoLayout);
        jPanelAvalicaoLayout.setHorizontalGroup(
            jPanelAvalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAvalicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabeOpenAV)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelAvalicaoLayout.setVerticalGroup(
            jPanelAvalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAvalicaoLayout.createSequentialGroup()
                .addGroup(jPanelAvalicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAvalicaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanelAvalicaoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabeOpenAV)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFicha.setToolTipText("Ficha treino");
        jPanelFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelFichaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelFichaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelFichaMousePressed(evt);
            }
        });

        jLabeOpenFicha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeOpenFicha.setForeground(new java.awt.Color(45, 118, 232));
        jLabeOpenFicha.setText("Abrir ficha treino");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Inspection_50px_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanelFichaLayout = new javax.swing.GroupLayout(jPanelFicha);
        jPanelFicha.setLayout(jPanelFichaLayout);
        jPanelFichaLayout.setHorizontalGroup(
            jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabeOpenFicha)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelFichaLayout.setVerticalGroup(
            jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabeOpenFicha)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanelAdicinaisLayout = new javax.swing.GroupLayout(jPanelAdicinais);
        jPanelAdicinais.setLayout(jPanelAdicinaisLayout);
        jPanelAdicinaisLayout.setHorizontalGroup(
            jPanelAdicinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicinaisLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanelAdicinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAdicinaisLayout.createSequentialGroup()
                        .addGroup(jPanelAdicinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAdicinaisLayout.createSequentialGroup()
                                .addComponent(jLabeAV)
                                .addGap(212, 212, 212))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdicinaisLayout.createSequentialGroup()
                                .addComponent(jPanelAvalicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)))
                        .addGroup(jPanelAdicinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFicha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelFicha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAdicinaisLayout.createSequentialGroup()
                        .addGroup(jPanelAdicinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelObjetivo)
                            .addComponent(jScrollObj, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(jPanelAdicinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelObs)
                            .addComponent(jScrollPaneObs)))
                    .addComponent(jLabelDados, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanelAdicinaisLayout.setVerticalGroup(
            jPanelAdicinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicinaisLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelDados)
                .addGap(28, 28, 28)
                .addGroup(jPanelAdicinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeAV)
                    .addComponent(jLabelFicha))
                .addGap(18, 18, 18)
                .addGroup(jPanelAdicinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAvalicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelAdicinaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdicinaisLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelObjetivo)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollObj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAdicinaisLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabelObs)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Adicionais", jPanelAdicinais);

        jPanelPagamentos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPagamentos.setToolTipText("Pagamentos do aluno");

        jLabelPagamentos.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabelPagamentos.setForeground(new java.awt.Color(45, 118, 232));
        jLabelPagamentos.setText("Pagamentos");

        jTable1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Historico da conta", "Valor", "Data de Vencimento", "Data do Pagamento", "Forma"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonSalvar1.setBackground(new java.awt.Color(45, 118, 232));
        jButtonSalvar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonSalvar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar1.setText("Lançar");
        jButtonSalvar1.setToolTipText("Lançar pagamento");
        jButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPagamentosLayout = new javax.swing.GroupLayout(jPanelPagamentos);
        jPanelPagamentos.setLayout(jPanelPagamentosLayout);
        jPanelPagamentosLayout.setHorizontalGroup(
            jPanelPagamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagamentosLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanelPagamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanelPagamentosLayout.setVerticalGroup(
            jPanelPagamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagamentosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelPagamentos)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pagamentos", jPanelPagamentos);

        jButtonSalvar.setBackground(new java.awt.Color(45, 118, 232));
        jButtonSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(45, 118, 232));
        jButtonCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackLayout = new javax.swing.GroupLayout(jPanelBack);
        jPanelBack.setLayout(jPanelBackLayout);
        jPanelBackLayout.setHorizontalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanelBackLayout.setVerticalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackLayout.createSequentialGroup()
                .addComponent(jPanelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(716, 692));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jFormattedTextFieldDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDNActionPerformed

    private void jFormattedTextFieldCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCEPActionPerformed

    private void jTextFieldRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRGActionPerformed

    private void jComboBoxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUFActionPerformed

    private void jFormattedTextFieldCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCelularActionPerformed

    private void jTextFieldLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLogradouroActionPerformed

    private void jTextFieldCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeActionPerformed

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jComboBoxSexo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexo1ActionPerformed

    private void jFormattedTextFieldCPF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPF1ActionPerformed

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    private void jTextFieldemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldemailActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
        new AlunosHomeJFrame().show();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(a.getId()==0)
            a=Projeto_GYM.fachada.cadastrarAluno(getAluno());
        else
            Projeto_GYM.fachada.editarAluno(getAluno());
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jPanelAvalicaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAvalicaoMouseEntered
        HomeJFrame.setColor(jPanelAvalicao);
    }//GEN-LAST:event_jPanelAvalicaoMouseEntered

    private void jPanelAvalicaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAvalicaoMouseExited
        HomeJFrame.resetColor(jPanelAvalicao);
    }//GEN-LAST:event_jPanelAvalicaoMouseExited

    private void jPanelFichaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFichaMouseExited
        HomeJFrame.resetColor(jPanelFicha);
    }//GEN-LAST:event_jPanelFichaMouseExited

    private void jPanelFichaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFichaMouseEntered
        HomeJFrame.setColor(jPanelFicha);
    }//GEN-LAST:event_jPanelFichaMouseEntered

    private void jButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvar1ActionPerformed
        new AlunosLancarFaturaJFrame(a).show();
    }//GEN-LAST:event_jButtonSalvar1ActionPerformed

    private void jPanelAvalicaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAvalicaoMousePressed
//        this.setVisible(false);
        if((a.getId()==0||a==null))//Fazer a restrição de acesso
            Mensagem.exibirMensagem("Cadastre o aluno antes de fazer a avaliação física");
        else
            new AlunosAvaliacaoHomeJFrame(a).show();
    }//GEN-LAST:event_jPanelAvalicaoMousePressed

    private void jPanelFichaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFichaMousePressed
//        this.setVisible(false);
        new AlunosFichaHomeJFrame().show();
    }//GEN-LAST:event_jPanelFichaMousePressed

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSalvar1;
    private javax.swing.JComboBox<String> jComboBoxSexo1;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JComboBox<String> jComboBoxUF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldDN;
    private javax.swing.JLabel jLabeAV;
    private javax.swing.JLabel jLabeAlunos;
    private javax.swing.JLabel jLabeOpenAV;
    private javax.swing.JLabel jLabeOpenFicha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelDN;
    private javax.swing.JLabel jLabelDados;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFicha;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelObjetivo;
    private javax.swing.JLabel jLabelObs;
    private javax.swing.JLabel jLabelPagamentos;
    private javax.swing.JLabel jLabelRg;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelUF;
    private javax.swing.JPanel jPanelAdicinais;
    private javax.swing.JPanel jPanelAvalicao;
    private javax.swing.JPanel jPanelBack;
    private javax.swing.JPanel jPanelBlue;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelFicha;
    private javax.swing.JPanel jPanelPagamentos;
    private javax.swing.JScrollPane jScrollObj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneObs;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaObj;
    private javax.swing.JTextArea jTextAreaObs;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldemail;
    // End of variables declaration//GEN-END:variables

    public Aluno getAluno(){
        Date d = Util.getDate(getjFormattedTextFieldDN().getText());
        int num = Integer.parseInt(getjTextFieldNumero().getText());
        
        a.setCpf(this.getjFormattedTextFieldCPF1().getText());
        a.setData_nascimento(d);
        a.setNome(getjTextFieldNome().getText());
        a.setSexo(getjComboBoxSexo1().getSelectedItem().toString()+"");
        a.setStatus(getjComboBoxStatus().getSelectedItem()+"");
        a.setRg(getjTextFieldRG().getText());
        a.setEmail(getjTextFieldemail().getText());
        a.setCelular(getjFormattedTextFieldCelular().getText());
        //Acrescentar campo de data de vencimento da mensalidade
              
        
        a.getEndereco().setBairro(getjTextFieldBairro().getText());
        a.getEndereco().setCep(getjFormattedTextFieldCEP().getText());
        a.getEndereco().setCidade(getjTextFieldCidade().getText());
        a.getEndereco().setLogradouro(getjTextFieldLogradouro().getText());
        a.getEndereco().setNum(num);
        a.getEndereco().setUf(getjComboBoxUF().getSelectedItem()+"");
        
        return a;
    }
    
    public void setAluno(Aluno a){
//        int num = Integer.parseInt(getjTextFieldNumero().getText());
        this.a=a;
        jFormattedTextFieldCPF1.setText(a.getCpf());
        getjFormattedTextFieldDN().setText(Util.getDateString(a.getData_nascimento()));
        getjTextFieldNome().setText(a.getNome());
        getjComboBoxSexo1().setSelectedItem(a.getSexo());
        getjComboBoxStatus().setSelectedItem(a.getStatus());
        getjTextFieldRG().setText(a.getRg());
        getjTextFieldemail().setText(a.getEmail());
        getjFormattedTextFieldCelular().setText(a.getCelular());
        //Acrescentar campo de data de vencimento da mensalidade
        
        getjTextFieldBairro().setText(a.getEndereco().getBairro());
        getjFormattedTextFieldCEP().setText(a.getEndereco().getCep());
        getjTextFieldCidade().setText(a.getEndereco().getCidade());
        getjTextFieldLogradouro().setText( a.getEndereco().getLogradouro());
        jTextFieldNumero.setText(a.getEndereco().getNum()+"");
        getjComboBoxUF().setSelectedItem(a.getEndereco().getUf());
    }
    
    public JComboBox<String> getjComboBoxSexo1() {
        return jComboBoxSexo1;
    }

    public JComboBox<String> getjComboBoxStatus() {
        return jComboBoxStatus;
    }

    public JComboBox<String> getjComboBoxUF() {
        return jComboBoxUF;
    }

    public JFormattedTextField getjFormattedTextFieldCEP() {
        return jFormattedTextFieldCEP;
    }

    public JFormattedTextField getjFormattedTextFieldCPF1() {
        return jFormattedTextFieldCPF1;
    }

    public JFormattedTextField getjFormattedTextFieldCelular() {
        return jFormattedTextFieldCelular;
    }

    public JFormattedTextField getjFormattedTextFieldDN() {
        return jFormattedTextFieldDN;
    }

    public JTextField getjTextFieldBairro() {
        return jTextFieldBairro;
    }

    public JTextField getjTextFieldCidade() {
        return jTextFieldCidade;
    }

    public JTextField getjTextFieldId() {
        return jTextFieldId;
    }

    public JTextField getjTextFieldLogradouro() {
        return jTextFieldLogradouro;
    }

    public JTextField getjTextFieldNome() {
        return jTextFieldNome;
    }

    public JTextField getjTextFieldRG() {
        return jTextFieldRG;
    }

    public JTextField getjTextFieldemail() {
        return jTextFieldemail;
    }

    public JTextField getjTextFieldNumero() {
        return jTextFieldNumero;
    }

    public JPanel getjPanelCadastro() {
        return jPanelCadastro;
    }

    

}
