/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import app.Projeto_GYM;
import controller.LoginControlador;
import javax.swing.JPanel;

/**
 *
 * @author Insinuante
 */
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrameHome
     */
    public HomeJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jPanelCabecario = new javax.swing.JPanel();
        jLabeAcademia = new javax.swing.JLabel();
        jLabeGym = new javax.swing.JLabel();
        jLabeLogout = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jSeparator = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabeAcademia1 = new javax.swing.JLabel();
        jLabeSair = new javax.swing.JLabel();
        jLabeConfig = new javax.swing.JLabel();
        jPanelAlunos = new javax.swing.JPanel();
        jLabelAlunos = new javax.swing.JLabel();
        jLabelIconAlunos = new javax.swing.JLabel();
        jPanelFuncionarios = new javax.swing.JPanel();
        jLabellFuncionarios = new javax.swing.JLabel();
        jLabelIconlFuncionarios = new javax.swing.JLabel();
        jPanelRelatorio = new javax.swing.JPanel();
        jLabelFinanceiro = new javax.swing.JLabel();
        jLabelIconFinanceiro = new javax.swing.JLabel();
        jPanelInfo = new javax.swing.JPanel();
        jLabellInfo = new javax.swing.JLabel();
        jLabelIconlInfo = new javax.swing.JLabel();
        jPanelExercicio = new javax.swing.JPanel();
        jLabellExercicios = new javax.swing.JLabel();
        jLabelIconlExer = new javax.swing.JLabel();
        jPanelFinanceiro = new javax.swing.JPanel();
        jLabelFinanceiro1 = new javax.swing.JLabel();
        jLabelIconFinanceiro1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Início");
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBackground.setVerifyInputWhenFocusTarget(false);

        jPanelCabecario.setBackground(new java.awt.Color(45, 118, 232));

        jLabeAcademia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeAcademia.setForeground(new java.awt.Color(255, 255, 255));
        jLabeAcademia.setText("Gestão de Academia");

        jLabeGym.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 55)); // NOI18N
        jLabeGym.setForeground(new java.awt.Color(255, 255, 255));
        jLabeGym.setText("GYM");

        jLabeLogout.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabeLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabeLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Logout_Rounded_Up_30px_1.png"))); // NOI18N
        jLabeLogout.setToolTipText("Logout");
        jLabeLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabeLogoutMousePressed(evt);
            }
        });

        jTextFieldPesquisar.setBackground(new java.awt.Color(45, 118, 232));
        jTextFieldPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPesquisar.setToolTipText("Digite texto para pesquisa");
        jTextFieldPesquisar.setBorder(null);
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search_20px_1.png"))); // NOI18N
        jLabel1.setToolTipText("Pesquisar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3.png"))); // NOI18N

        jLabeAcademia1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeAcademia1.setForeground(new java.awt.Color(255, 255, 255));
        jLabeAcademia1.setText("de Musculação");

        jLabeSair.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabeSair.setForeground(new java.awt.Color(255, 255, 255));
        jLabeSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Cancel_30px_1.png"))); // NOI18N
        jLabeSair.setToolTipText("Sair");
        jLabeSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabeSairMousePressed(evt);
            }
        });

        jLabeConfig.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabeConfig.setForeground(new java.awt.Color(255, 255, 255));
        jLabeConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Settings_30px_1.png"))); // NOI18N
        jLabeConfig.setToolTipText("Configurações");
        jLabeConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabeConfigMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCabecarioLayout = new javax.swing.GroupLayout(jPanelCabecario);
        jPanelCabecario.setLayout(jPanelCabecarioLayout);
        jPanelCabecarioLayout.setHorizontalGroup(
            jPanelCabecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabecarioLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanelCabecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabeGym)
                    .addGroup(jPanelCabecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelCabecarioLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabeAcademia1))
                        .addComponent(jLabeAcademia)))
                .addGroup(jPanelCabecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCabecarioLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCabecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator)
                            .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCabecarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabeConfig)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabeLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabeSair)
                        .addGap(23, 23, 23))))
        );
        jPanelCabecarioLayout.setVerticalGroup(
            jPanelCabecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabecarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCabecarioLayout.createSequentialGroup()
                .addGroup(jPanelCabecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCabecarioLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabeGym))
                    .addGroup(jPanelCabecarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCabecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabeLogout)
                            .addComponent(jLabeConfig)
                            .addComponent(jLabeSair))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCabecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCabecarioLayout.createSequentialGroup()
                        .addGroup(jPanelCabecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCabecarioLayout.createSequentialGroup()
                        .addComponent(jLabeAcademia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabeAcademia1)))
                .addGap(46, 46, 46))
        );

        jPanelAlunos.setToolTipText("Cadastro de alunos");
        jPanelAlunos.setPreferredSize(new java.awt.Dimension(140, 120));
        jPanelAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAlunosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAlunosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelAlunosMousePressed(evt);
            }
        });

        jLabelAlunos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelAlunos.setForeground(new java.awt.Color(45, 118, 232));
        jLabelAlunos.setText("Alunos");

        jLabelIconAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_52px.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAlunosLayout = new javax.swing.GroupLayout(jPanelAlunos);
        jPanelAlunos.setLayout(jPanelAlunosLayout);
        jPanelAlunosLayout.setHorizontalGroup(
            jPanelAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlunosLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanelAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlunosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAlunos))
                    .addComponent(jLabelIconAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanelAlunosLayout.setVerticalGroup(
            jPanelAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlunosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelIconAlunos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAlunos)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelFuncionarios.setToolTipText("Cadastro de funcionários");
        jPanelFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelFuncionariosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelFuncionariosMousePressed(evt);
            }
        });

        jLabellFuncionarios.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabellFuncionarios.setForeground(new java.awt.Color(45, 118, 232));
        jLabellFuncionarios.setText("Funcionários");

        jLabelIconlFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/crachá-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanelFuncionariosLayout = new javax.swing.GroupLayout(jPanelFuncionarios);
        jPanelFuncionarios.setLayout(jPanelFuncionariosLayout);
        jPanelFuncionariosLayout.setHorizontalGroup(
            jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionariosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelIconlFuncionarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFuncionariosLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabellFuncionarios)
                .addGap(32, 32, 32))
        );
        jPanelFuncionariosLayout.setVerticalGroup(
            jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionariosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelIconlFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabellFuncionarios)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelRelatorio.setToolTipText("Financeiro");
        jPanelRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRelatorioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelRelatorioMousePressed(evt);
            }
        });

        jLabelFinanceiro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelFinanceiro.setForeground(new java.awt.Color(45, 118, 232));
        jLabelFinanceiro.setText("Relatórios");

        jLabelIconFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_64px.png"))); // NOI18N

        javax.swing.GroupLayout jPanelRelatorioLayout = new javax.swing.GroupLayout(jPanelRelatorio);
        jPanelRelatorio.setLayout(jPanelRelatorioLayout);
        jPanelRelatorioLayout.setHorizontalGroup(
            jPanelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFinanceiro)
                    .addComponent(jLabelIconFinanceiro))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelRelatorioLayout.setVerticalGroup(
            jPanelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelIconFinanceiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFinanceiro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelInfo.setToolTipText("Infomações sobre o sistema");
        jPanelInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelInfoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelInfoMousePressed(evt);
            }
        });

        jLabellInfo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabellInfo.setForeground(new java.awt.Color(45, 118, 232));
        jLabellInfo.setText("Infomação");

        jLabelIconlInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/about.png"))); // NOI18N

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelIconlInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabellInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelIconlInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabellInfo)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelExercicio.setToolTipText("Cadastro de exercícios");
        jPanelExercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelExercicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelExercicioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelExercicioMousePressed(evt);
            }
        });

        jLabellExercicios.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabellExercicios.setForeground(new java.awt.Color(45, 118, 232));
        jLabellExercicios.setText("Exercícios");

        jLabelIconlExer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Blue.png"))); // NOI18N

        javax.swing.GroupLayout jPanelExercicioLayout = new javax.swing.GroupLayout(jPanelExercicio);
        jPanelExercicio.setLayout(jPanelExercicioLayout);
        jPanelExercicioLayout.setHorizontalGroup(
            jPanelExercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExercicioLayout.createSequentialGroup()
                .addGroup(jPanelExercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExercicioLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabelIconlExer))
                    .addGroup(jPanelExercicioLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabellExercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanelExercicioLayout.setVerticalGroup(
            jPanelExercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExercicioLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelIconlExer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabellExercicios)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelFinanceiro.setToolTipText("Financeiro");
        jPanelFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelFinanceiroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelFinanceiroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelFinanceiroMousePressed(evt);
            }
        });

        jLabelFinanceiro1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelFinanceiro1.setForeground(new java.awt.Color(45, 118, 232));
        jLabelFinanceiro1.setText("Financeiro");

        jLabelIconFinanceiro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fin50.png"))); // NOI18N

        javax.swing.GroupLayout jPanelFinanceiroLayout = new javax.swing.GroupLayout(jPanelFinanceiro);
        jPanelFinanceiro.setLayout(jPanelFinanceiroLayout);
        jPanelFinanceiroLayout.setHorizontalGroup(
            jPanelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinanceiroLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFinanceiro1)
                    .addComponent(jLabelIconFinanceiro1))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelFinanceiroLayout.setVerticalGroup(
            jPanelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinanceiroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelIconFinanceiro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFinanceiro1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jPanelAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jPanelFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jPanelRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelExercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(140, 140, 140))
            .addComponent(jPanelCabecario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addComponent(jPanelCabecario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelExercicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExercicioMousePressed
        new ExerciciosHomeJFrame().show();
    }//GEN-LAST:event_jPanelExercicioMousePressed

    private void jPanelExercicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExercicioMouseExited
        resetColor(jPanelExercicio);
    }//GEN-LAST:event_jPanelExercicioMouseExited

    private void jPanelExercicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExercicioMouseEntered
        setColor(jPanelExercicio);
    }//GEN-LAST:event_jPanelExercicioMouseEntered

    private void jPanelInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInfoMousePressed
        new InformacaoJFrame().show();
    }//GEN-LAST:event_jPanelInfoMousePressed

    private void jPanelInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInfoMouseExited
        resetColor(jPanelInfo);
    }//GEN-LAST:event_jPanelInfoMouseExited

    private void jPanelInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInfoMouseEntered
        setColor(jPanelInfo);
    }//GEN-LAST:event_jPanelInfoMouseEntered

    private void jPanelRelatorioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioMousePressed
        new RelatorioJFrame().show();
    }//GEN-LAST:event_jPanelRelatorioMousePressed

    private void jPanelRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioMouseExited
        resetColor(jPanelRelatorio);
    }//GEN-LAST:event_jPanelRelatorioMouseExited

    private void jPanelRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioMouseEntered
        setColor(jPanelRelatorio);
    }//GEN-LAST:event_jPanelRelatorioMouseEntered

    private void jPanelFuncionariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionariosMousePressed
        new FuncionariosJFrame().show();
    }//GEN-LAST:event_jPanelFuncionariosMousePressed

    private void jPanelFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionariosMouseExited
        resetColor(jPanelFuncionarios);
    }//GEN-LAST:event_jPanelFuncionariosMouseExited

    private void jPanelFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionariosMouseEntered
        setColor(jPanelFuncionarios);
    }//GEN-LAST:event_jPanelFuncionariosMouseEntered

    private void jPanelAlunosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlunosMousePressed
        new AlunosHomeJFrame().show();
    }//GEN-LAST:event_jPanelAlunosMousePressed

    private void jPanelAlunosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlunosMouseExited
        resetColor(jPanelAlunos);
    }//GEN-LAST:event_jPanelAlunosMouseExited

    private void jPanelAlunosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlunosMouseEntered
        setColor(jPanelAlunos);
    }//GEN-LAST:event_jPanelAlunosMouseEntered

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jLabeLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeLogoutMousePressed
        dispose();
        // ESTA CERTO?
        LoginJFrame login = new LoginJFrame();
        login.setVisible(true);
        new LoginControlador(login);
    }//GEN-LAST:event_jLabeLogoutMousePressed

    private void jPanelFinanceiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFinanceiroMouseEntered
        setColor(jPanelFinanceiro);
    }//GEN-LAST:event_jPanelFinanceiroMouseEntered

    private void jPanelFinanceiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFinanceiroMouseExited
        resetColor(jPanelFinanceiro);
    }//GEN-LAST:event_jPanelFinanceiroMouseExited

    private void jPanelFinanceiroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFinanceiroMousePressed
        new FincanceiroJFrame().show();
    }//GEN-LAST:event_jPanelFinanceiroMousePressed

    private void jLabeSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeSairMousePressed
       System.exit(0);
    }//GEN-LAST:event_jLabeSairMousePressed

    private void jLabeConfigMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeConfigMousePressed
        new AcademiaCadastroJFrame().show();
    }//GEN-LAST:event_jLabeConfigMousePressed

    // ME: 
    public static void setColor(JPanel panel){
     panel.setBackground(new java.awt.Color(197, 197, 197));
    }
 
 
    public static void resetColor(JPanel panel){
     panel.setBackground(new java.awt.Color(240,240,240));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabeAcademia;
    private javax.swing.JLabel jLabeAcademia1;
    private javax.swing.JLabel jLabeConfig;
    private javax.swing.JLabel jLabeGym;
    private javax.swing.JLabel jLabeLogout;
    private javax.swing.JLabel jLabeSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAlunos;
    private javax.swing.JLabel jLabelFinanceiro;
    private javax.swing.JLabel jLabelFinanceiro1;
    private javax.swing.JLabel jLabelIconAlunos;
    private javax.swing.JLabel jLabelIconFinanceiro;
    private javax.swing.JLabel jLabelIconFinanceiro1;
    private javax.swing.JLabel jLabelIconlExer;
    private javax.swing.JLabel jLabelIconlFuncionarios;
    private javax.swing.JLabel jLabelIconlInfo;
    private javax.swing.JLabel jLabellExercicios;
    private javax.swing.JLabel jLabellFuncionarios;
    private javax.swing.JLabel jLabellInfo;
    private javax.swing.JPanel jPanelAlunos;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelCabecario;
    private javax.swing.JPanel jPanelExercicio;
    private javax.swing.JPanel jPanelFinanceiro;
    private javax.swing.JPanel jPanelFuncionarios;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelRelatorio;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
